### ISSUE TITLE
I've got the following error when running babel-watch

### ISSUE THREAD

**Issue by sibelius** [kmagiera/babel-watch#89] opened 2018-11-19 14:10 UTC
```jsx
babel-watch/babel-watch.js:30
program.option('-p, --plugins [string]', '', babel.util.list);
                                                        ^

TypeError: Cannot read property 'list' of undefined
    at Object.<anonymous> (/Users/sibelius/Dev/entria/app/node_modules/babel-watch/babel-watch.js:30:57)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
error Command failed with exit code 1.
```

**Comment by SterlingVix** [comment] 2018-11-21 21:22
^^^ Duplicate of:
https://github.com/kmagiera/babel-watch/issues/65

But a valid issue.

**Comment by STRML** [comment] 2021-01-05 17:58
This is fixed. We no longer use `babel.util`.

**Closed as completed by STRML** 2021-01-05 17:58 UTC
